#+STARTUP: overview

* SwiftMac
** Configuration / Install
*** swiftmac.tar.gz (binaries)

Copy the extracted files to the $EMACSPEAK_DIR/servers and
then add the swiftmac server to your emacs config, for more
info see: [[file:Readme.emacspeak.org][Readme.emacspeak.org]]

*** source based

Otherwise see: [[file:Readme.emacspeak.org][Readme.emacspeak.org]]

** Bonus configuration stuff

#+BEGIN_SRC emacs-lisp
  ; control volume
  ; these are between 0.0 and 1.0
  (setenv "SWIFTMAC_TONE_VOLUME" "0.1")
  (setenv "SWIFTMAC_SOUND_VOLUME" "0.1")
  (setenv "SWIFTMAC_VOICE_VOLUME" "1.0")
  ; examples of messing with voices
  (swiftmac-define-voice voice-bolden "[{voice en_US:Fred}] [[pitch 0.8]]")
  (swiftmac-define-voice voice-animate "[{voice en-US:Kit}] [[pitch 1]]")
  (swiftmac-define-voice voice-animate-extra "[{voice en-US:Kit}] [[pitch 1.5 ]]")
  (swiftmac-define-voice voice-lighten "[{voice en-AU:Matilda}] [[pitch 1]]")
  (swiftmac-define-voice voice-lighten-extra "[{voice en-AU:Matilda}] [[pitch 1.1]]")
  (swiftmac-define-voice voice-smoothen "[{voice en-UK:Daniel}] [[pitch 1]]")
  (swiftmac-define-voice voice-monotone "[{voice en-US:Eddy}] [[pitch 1]]")
  (swiftmac-define-voice voice-monotone-extra "[{voice en-US:Eddy}] [[pitch 1.5]]")
#+END_SRC

** Multi-Device and Channel Routing

SwiftMac supports routing different audio types to different physical devices AND channels. All four audio types can be independently configured:
- Speech (main spoken output)
- Notifications (auditory icons/beeps)
- Tones (generated tones)
- Sound effects (played audio files)

*** Finding Your Device IDs

Run this to list available audio output devices:

#+BEGIN_SRC shell
make list-devices
#+END_SRC

Example output:
#+BEGIN_EXAMPLE
[DEFAULT] DeviceID: 125 | "Audioengine D1" | Channels: 2
          DeviceID: 110 | "LG Ultra HD" | Channels: 2
          DeviceID: 89 | "MacBook Pro Speakers" | Channels: 2
#+END_EXAMPLE

*** Configuration Format

Set environment variables in your Emacs init file (BEFORE loading emacspeak):

#+BEGIN_SRC emacs-lisp
  (setenv "SWIFTMAC_<TYPE>_DEVICE_AND_CHANNEL" "<deviceID>:<channel>")
#+END_SRC

Where:
- =<TYPE>=: SPEECH, NOTIFICATION, TONE, or SOUNDEFFECT
- =<deviceID>=: Numeric ID from =make list-devices= (or 0 for system default)
- =<channel>=: left, right, or both

*** Example Configurations

**** All Audio to One Device (Simple Setup)
#+BEGIN_SRC emacs-lisp
  ; Everything to Audioengine D1, stereo
  (setenv "SWIFTMAC_SPEECH_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_NOTIFICATION_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_TONE_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_SOUNDEFFECT_DEVICE_AND_CHANNEL" "125:both")
#+END_SRC

**** Separate Devices for Speech and Notifications
#+BEGIN_SRC emacs-lisp
  ; Speech to headphones, notifications to monitor speakers
  (setenv "SWIFTMAC_SPEECH_DEVICE_AND_CHANNEL" "125:both")  ; Audioengine D1
  (setenv "SWIFTMAC_NOTIFICATION_DEVICE_AND_CHANNEL" "110:both")  ; LG Ultra HD
  (setenv "SWIFTMAC_TONE_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_SOUNDEFFECT_DEVICE_AND_CHANNEL" "110:both")

  ; IMPORTANT: Enable notification server for multi-device routing
  (setopt tts-notification-device "left")
#+END_SRC

**** Same Device, Different Channels
#+BEGIN_SRC emacs-lisp
  ; Speech in both ears, notifications in left ear only
  (setenv "SWIFTMAC_SPEECH_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_NOTIFICATION_DEVICE_AND_CHANNEL" "125:left")
  (setenv "SWIFTMAC_TONE_DEVICE_AND_CHANNEL" "125:both")
  (setenv "SWIFTMAC_SOUNDEFFECT_DEVICE_AND_CHANNEL" "125:left")

  (setopt tts-notification-device "left")  ; Enable notification server
#+END_SRC

**** All Four Audio Types to Different Outputs
#+BEGIN_SRC emacs-lisp
  ; Maximum separation for complex audio setups
  (setenv "SWIFTMAC_SPEECH_DEVICE_AND_CHANNEL" "125:both")  ; Speech -> Audioengine D1
  (setenv "SWIFTMAC_NOTIFICATION_DEVICE_AND_CHANNEL" "110:left")  ; Notifications -> LG left
  (setenv "SWIFTMAC_TONE_DEVICE_AND_CHANNEL" "89:both")  ; Tones -> MacBook speakers
  (setenv "SWIFTMAC_SOUNDEFFECT_DEVICE_AND_CHANNEL" "110:right")  ; Sounds -> LG right

  (setopt tts-notification-device "left")  ; Enable notification server
#+END_SRC

*** Runtime Channel Commands

Change ONLY the channel (not device) on the fly:

- =tts_set_speech_channel {left|right|both}=
- =tts_set_notification_channel {left|right|both}=

Note: Runtime device switching (changing the physical device) is not yet supported. Restart Emacs to change devices.

*** How Multi-Device Routing Works

Emacspeak spawns two separate swiftmac processes:
1. *Speech process* (main): Handles regular speech output
2. *Notification process*: Handles auditory icons and notifications

The =tts-notification-device= setting triggers Emacspeak to spawn the second process with =SWIFTMAC_AUDIO_TARGET= set, which swiftmac detects as notification mode.

Each process reads its own device configuration from the environment variables, allowing speech and notifications to output to different physical devices.

For more details, see =MULTI-DEVICE-SETUP.md=.

** Introduction 

This is an emacspeak server written in swift intended to be as async as 
reasonable, fast and responsive.

Unless you are a developer or interested in becoming one, you probably 
want to use the version bundled with emacspeak, I keep that copy up to 
date with this one fairly consistently. 

** Hacking

The recommended workflow is to symlink the swiftmac binary under either
.build/release/swiftmac or ./build/debug/swiftmac (depending which you are building) to your emacspeak servers directory. 

then just
#+begin_src shell
make
#+end_src

for debug or

#+begin_src shell
make release
#+end_src

to build a fresh binary.

I will likely remove make install in the future, as it is a bit fidgety, but I 
will leave it in for now. 

** Having Trouble?

*** It emits warnings and notes

I am aware of the current warnings, it is a goal to get it to build completely 
clean but tthat is not a priority right now, getting to v2 is the priority.

*** Double-Speaking

If you are hearing stuff twice, ensure that mac-ignore-accessibility is set 
and your emacs version supports it. If that doesn't work, you can use the 
VoiceOver Utility that comes with MacOS to create an activity for Emacs.app 
to turn off voiceover while in the Emacs window.  This only works if you are
using a windowed version of Emacs (not terminal version). 

** Design

The server intends to provide primitives to support all the features used by
emacspeak and swiftmac-voices.el.


*** Supported Commands

These are the commands sent via stdin and on thier own line.

- =a=: queue audio icon
- =c=: queue code
- =d=: dispatch queue
- =l=: instant letter
- =p=: instant audio icon
- =q=: queue speech
- =s=: stop all (confirm with list)_
- =sh=: queue silence
- =t=: queue tone
- =tts_pause=: instant pause speech engine (should stop?)
- =tts_reset=: queue reset (to defaults?)
- =tts_resume=: instant resume speech engine
- =tts_say=: instant say no additional tweaking
- =tts_set_character_scale=: queue char scale change
- =tts_set_punctuations=: queue punct change
- =tts_set_speech_rate=: queue rate change
- =tts_split_caps=: queue split caps change
- =tts_sync_state=: [decomp] queue multiple settings change
- =version=: [decomp] say tts version

Not Implemented yet:
- =set_next_lang=:
- =set_previous_lang=:
- =set_lang=
- =set_preferred_lang=


Engine Specific:
- =tts_exit=: instant exit
- =tts_set_pitch_multiplier=: .5 to 2 pitch multiplier
- =tts_set_sound_volume=: 0 to 1 (1 being 100% sound volume)
- =tts_set_tone_volume=: 0 to 1 (1 being 100% tone volume)
- =tts_set_voice=: queue voice change
- =tts_set_voice_volume=: 0 to 1 (1 being 100% voice volume)

Broken:
- =tts_allcaps_beep=: queue caps beep change, setting only works on typing
  input


*** Supported Embeddings

These are converted by the preprocessor into tts_ commands.

- [*] - queue silence in place of this

** Goals

1. The server should be as dumb as possible.
2. Major decisions should be configurable in lisp.
3. System should be "usable by default" meaing:
   once it builds, it works.
4. Server will depend on only clearly defined and 
   checked at compile time things. No secret deps
   on command line tools.
